"""
Standard Beam Search and Greedy Inference for TAMER model.

Key features & fixes:
- Fully batched greedy decoding for massive evaluation speedups.
- Sequence deduplication in beam search (Bug 17) to maximize effective beam width.
- Length penalty applied to prevent the model from favoring abnormally short sequences.
"""

import torch
import torch.nn.functional as F
from typing import List, Optional
import logging

logger = logging.getLogger("TAMER.Inference")


@torch.no_grad()
def beam_search(
    model,
    image: torch.Tensor,
    sos_id: int,
    eos_id: int,
    pad_id: int,
    beam_width: int = 5,
    max_len: int = 200,
    length_penalty: float = 0.6,
    device: torch.device = None,
) -> List[int]:
    """
    Batched beam search decoding for a single image with sequence deduplication.
    
    Args:
        model: TAMERModel instance
        image: (1, 3, H, W) input image tensor
        sos_id: Start-of-sequence token ID
        eos_id: End-of-sequence token ID
        pad_id: Padding token ID
        beam_width: Number of beams
        max_len: Maximum output sequence length
        length_penalty: Penalty for short sequences (>0 encourages longer output)
        device: Device for tensors
    
    Returns:
        List of token IDs (excluding SOS and EOS)
    """
    model.eval()
    if device is None:
        device = image.device
    
    # Encode image once
    memory = model.encode(image)  # (1, S, D)
    
    # Initialize beams: list of (tokens, log_prob)
    beams = [([sos_id], 0.0)]
    completed = []
    
    for step in range(max_len):
        if not beams:
            break
            
        # Filter out completed beams
        active_beams = []
        for tokens, score in beams:
            if tokens[-1] == eos_id:
                length = len(tokens) - 1  # Exclude SOS
                penalized_score = score / ((length ** length_penalty) if length > 0 else 1.0)
                completed.append((tokens, penalized_score))
            else:
                active_beams.append((tokens, score))
                
        if not active_beams:
            break
            
        # Batch the active beams together for a single forward pass
        num_active = len(active_beams)
        
        # (num_active, L)
        tgt_ids = torch.tensor([b[0] for b in active_beams], dtype=torch.long, device=device)
        
        # Expand memory to match the number of active beams
        # (num_active, S, D)
        batched_memory = memory.expand(num_active, -1, -1)
        
        L = tgt_ids.size(1)
        tgt_mask = model.decoder.generate_causal_mask(L, device)
        
        # Forward pass for all beams at once
        # logits: (num_active, L, V)
        logits = model.decoder(tgt_ids, batched_memory, tgt_mask)
        
        # We only care about the last token prediction
        # next_logits: (num_active, V)
        next_logits = logits[:, -1, :]
        log_probs = F.log_softmax(next_logits, dim=-1)  # (num_active, V)
        
        # Get top-k candidates for each beam
        # topk_log_probs, topk_indices: (num_active, beam_width)
        topk_log_probs, topk_indices = log_probs.topk(beam_width, dim=-1)
        
        all_candidates = []
        seen_sequences = set()
        
        for i in range(num_active):
            current_tokens, current_score = active_beams[i]
            for j in range(beam_width):
                new_token = topk_indices[i, j].item()
                new_score = current_score + topk_log_probs[i, j].item()
                
                candidate_tokens = current_tokens + [new_token]
                seq_tuple = tuple(candidate_tokens)
                
                # FIX: Deduplicate identical sequences generated by different beam paths
                if seq_tuple not in seen_sequences:
                    seen_sequences.add(seq_tuple)
                    all_candidates.append((candidate_tokens, new_score))
        
        # Select top beam_width candidates overall
        all_candidates.sort(key=lambda x: x[1], reverse=True)
        beams = all_candidates[:beam_width]
        
    # If no completed beams, take the best incomplete one
    if not completed:
        for tokens, score in beams:
            length = len(tokens) - 1
            penalized_score = score / ((length ** length_penalty) if length > 0 else 1.0)
            completed.append((tokens, penalized_score))
    
    # Select best
    completed.sort(key=lambda x: x[1], reverse=True)
    best_tokens = completed[0][0]
    
    # Remove SOS and EOS
    if best_tokens[0] == sos_id:
        best_tokens = best_tokens[1:]
    if best_tokens and best_tokens[-1] == eos_id:
        best_tokens = best_tokens[:-1]
    
    return best_tokens


@torch.no_grad()
def greedy_decode(
    model,
    images: torch.Tensor,
    sos_id: int,
    eos_id: int,
    max_len: int = 200,
    device: torch.device = None,
) -> List[List[int]]:
    """
    Batched greedy decoding for fast inference.
    
    Args:
        model: TAMERModel instance
        images: (B, 3, H, W) input image tensor
        sos_id: Start-of-sequence token ID
        eos_id: End-of-sequence token ID
        max_len: Maximum output sequence length
        device: Device for tensors
        
    Returns:
        List of Lists containing token IDs for each image in the batch
    """
    model.eval()
    if device is None:
        device = images.device
    
    B = images.size(0)
    memory = model.encode(images)  # (B, S, D)
    
    # Initialize tokens for the whole batch
    # (B, 1)
    tokens = torch.full((B, 1), sos_id, dtype=torch.long, device=device)
    
    # Keep track of which sequences in the batch have finished
    unfinished = torch.ones(B, dtype=torch.bool, device=device)
    
    for _ in range(max_len):
        L = tokens.size(1)
        tgt_mask = model.decoder.generate_causal_mask(L, device)
        
        # (B, L, V)
        logits = model.decoder(tokens, memory, tgt_mask)
        
        # Get the most likely next token for each sequence
        # (B,)
        next_tokens = logits[:, -1, :].argmax(dim=-1)
        
        # If a sequence is already finished, force it to predict EOS
        next_tokens = torch.where(unfinished, next_tokens, torch.tensor(eos_id, device=device))
        
        # Append to sequences
        tokens = torch.cat([tokens, next_tokens.unsqueeze(1)], dim=1)
        
        # Update unfinished mask
        unfinished = unfinished & (next_tokens != eos_id)
        
        # Early stopping if all sequences in the batch are finished
        if not unfinished.any():
            break
            
    # Convert to list of lists and remove SOS/EOS
    result = []
    tokens_list = tokens.cpu().tolist()
    
    for seq in tokens_list:
        # Remove SOS
        if seq[0] == sos_id:
            seq = seq[1:]
            
        # Truncate at first EOS
        if eos_id in seq:
            seq = seq[:seq.index(eos_id)]
            
        result.append(seq)
        
    return result